# Generated by Django 3.1 on 2020-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_draas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draas',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
