# Generated by Django 3.1 on 2020-08-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200818_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draas',
            options={'verbose_name': 'DRaaS', 'verbose_name_plural': 'DRaaS'},
        ),
        migrations.AlterModelOptions(
            name='iaas',
            options={'verbose_name': 'IaaS', 'verbose_name_plural': 'IaaS'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='riserva',
            name='price_aed',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='riserva',
            name='price_dollars',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='riserva',
            name='selling_price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
