# Generated by Django 3.1 on 2020-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200819_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
