# Generated by Django 3.1 on 2020-08-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_customer'),
        ('products', '0014_auto_20200829_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riserva_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('requested_items', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.partner')),
                ('riserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.riserva')),
            ],
        ),
        migrations.CreateModel(
            name='IaaS_DRaaS_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('requested_items', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.partner')),
            ],
        ),
    ]
